version: '3.8'

services:
  app:
    image: docker-spring-demo:0.0.1
    ports:
      - 2222:2222
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/userdb1?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: imtiaz
      SPRING_DATASOURCE_PASSWORD: imtiaz@1234
    depends_on:
      - db
      
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb1
      MYSQL_USER: imtiaz
      MYSQL_PASSWORD: imtiaz@1234
